export enum tagTypes {
  user = "user",
  department = "department",
  faculty = "faculty",
  student = "student",
  admin = "admin",
  academicSemester = "academicSemester",
  academicFaculty = "academicFaculty",
  academicDepartment = "academicDepartment",
  building = "building",
  room = "room",
  course = "course",
  semesterRegistration = "semesterRegistration",
  offeredCourse = "offeredCourse",
  offeredCourseSection = "offeredCourseSection",
}

export const tagsTypesList = [
  tagTypes.user,
  tagTypes.department,
  tagTypes.faculty,
  tagTypes.student,
  tagTypes.admin,
  tagTypes.academicSemester,
  tagTypes.academicFaculty,
  tagTypes.academicDepartment,
  tagTypes.building,
  tagTypes.room,
  tagTypes.course,
  tagTypes.semesterRegistration,
  tagTypes.offeredCourse,
  tagTypes.offeredCourseSection,
];
